### ISSUE TITLE
Reddit title encoding 

### ISSUE THREAD

**Issue by lezsakdomi** [Mino260806/MessengerPro#5] opened 2022-04-02 05:29 UTC
Hi!

Seems like reddit posts have encoding problems. The special characters in the title are wrong, but the body seems right.

![Screenshot_20220402-072358_Messenger](https://user-images.githubusercontent.com/8544161/161367877-982a2202-e077-4cc1-8b1d-669ac1ba0e80.png)

The title should read: "Elvittem a Fideszes szüleimet MZP gyűlésére... Sosem találjátok ki mi történt!"

The post from the screenshot: https://www.reddit.com/r/hungary/comments/ttxi7e/elvittem_a_fideszes_sz%C3%BCleimet_mzp_gy%C5%B1l%C3%A9s%C3%A9re_sosem/

I suggest you testing it with r/hungary, as we use a lot of diacritics in Hungarian.

I hope it will be an easy fix.

**Comment by lezsakdomi** [comment] 2022-04-02 08:24
Hmm this isn't a reddit only issue 🤔

**Comment by lezsakdomi** [comment] 2022-04-02 08:32
Hmm, seems like not only Reddit is affected 🤔

https://imgur.com/a/7jvof5y

**Comment by lezsakdomi** [comment] 2022-04-02 08:40
Hmm I experimented furthermore, probably some fancy Unicode character gets just recognized as star thus triggers bold font 🤔

**Comment by Mino260806** [comment] 2022-04-02 11:53
I understand the problem. This issue is related to non standard latin letters (ex with accents). I will fix it in the next patch. 
Thanks for reporting

**Comment by Mino260806** [comment] 2022-04-02 15:26
https://github.com/Mino260806/MessengerPro/commit/1458d9de2b9d424a1de5a5210fef3ae23dd9f147

**Comment by Mino260806** [comment] 2022-04-02 15:27
The issue is fixed in commit: https://github.com/Mino260806/MessengerPro/commit/1458d9de2b9d424a1de5a5210fef3ae23dd9f147

**Closed by Mino260806** 2022-04-02 15:27 UTC
Labels: bug
